FROM --platform=$BUILDPLATFORM imbios/bun-node:22-slim AS builder

WORKDIR /app

COPY bun.lock package.json ./
RUN bun install

COPY . .

RUN bun quasar prepare
RUN bun run build

FROM caddy:2-alpine AS runner

WORKDIR /srv

COPY --from=builder /app/dist/pwa   ./app

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 8080
